;
;==================================================================================================
;   MBC CONFIGURATION
;==================================================================================================
;
; THE COMPLETE SET OF DEFAULT CONFIGURATION SETTINGS FOR THIS PLATFORM ARE FOUND IN THE
; CFG_<PLT>.ASM INCLUDED FILE WHICH IS FOUND IN THE PARENT DIRECTORY.  THIS FILE CONTAINS
; COMMON CONFIGURATION SETTINGS THAT OVERRIDE THE DEFAULTS.  IT IS INTENDED THAT YOU MAKE
; YOUR CUSTOMIZATIONS IN THIS FILE AND JUST INHERIT ALL OTHER SETTINGS FROM THE DEFAULTS.
; EVEN BETTER, YOU CAN MAKE A COPY OF THIS FILE WITH A NAME LIKE <PLT>_XXX.ASM AND SPECIFY
; YOUR FILE IN THE BUILD PROCESS.
;
; THE SETTINGS BELOW ARE THE SETTINGS THAT ARE MOST COMMONLY MODIFIED FOR THIS PLATFORM.
; MANY OF THEM ARE EQUAL TO THE SETTINGS IN THE INCLUDED FILE, SO THEY DON'T REALLY DO
; ANYTHING AS IS.  THEY ARE LISTED HERE TO MAKE IT EASY FOR YOU TO ADJUST THE MOST COMMON
; SETTINGS.
;
; N.B., SINCE THE SETTINGS BELOW ARE REDEFINING VALUES ALREADY SET IN THE INCLUDED FILE,
; TASM INSISTS THAT YOU USE THE .SET OPERATOR AND NOT THE .EQU OPERATOR BELOW. ATTEMPTING
; TO REDEFINE A VALUE WITH .EQU BELOW WILL CAUSE TASM ERRORS!
;
; PLEASE REFER TO THE CUSTOM BUILD INSTRUCTIONS (README.TXT) IN THE SOURCE DIRECTORY (TWO
; DIRECTORIES ABOVE THIS ONE).
;
#DEFINE PLATFORM_NAME "Multi Board Computer"
#DEFINE	BOOT_DEFAULT	"H"		; DEFAULT BOOT LOADER CMD ON <CR> OR AUTO BOOT
;
#include "cfg_mbc.asm"
;
BATCOND		.SET	FALSE
;
PPIDEENABLE	.SET	TRUE		; PPIDE: ENABLE PARALLEL PORT IDE DISK DRIVER (PPIDE.ASM)
;
DSKYENABLE	.SET	TRUE		; ENABLES DSKY
DSKYMODE	.SET	DSKYMODE_NG	; DSKY VERTSION: DSKYMODE_[V1|NG]
DSKYOSC		.SET	1843200		; DSKY ON BOARD 8279 CLOCK
DSKYPPIBASE	.SET	$60		; BASE I/O ADDRESS OF DSKY PPI

CPUOSC		.SET	4000000		; CPU CLOCK 4MHz

RAMSIZE		.SET	1024		; INSTALLED RAM

FDENABLE	.SET	TRUE		; FD: ENABLE FLOPPY DISK DRIVER (FD.ASM)

DMAENABLE	.SET	TRUE		; DMA: ENABLE DMA DRIVER (DMA.ASM)
DMABASE		.SET	$E0		; DMA: DMA BASE ADDRESS
DMAMODE		.SET	DMAMODE_MBC	; DMA: DMA MODE (NONE|ECB|Z180|Z280|RC|MBC)

INTMODE		.SET	2			; SET INTERRUPT MODE 2 FOR Z80 CTCDART

UARTINTS	.SET	TRUE
UARTCFG		.SET	UARTCFG | SER_RTS

MDFFENABLE	.SET	TRUE		; MD: ENABLE FLASH FILE SYSTEM 

UARTDUAL	.SET	TRUE		; ENABLE DUART

CVDUMODE	.SET	CVDUMODE_MBC	; CVDU: MODE ENABLE Z80 VDC
CVDUMON		.SET	CVDUMON_CGA	; CVDU MONITOR SETUP

CPUSPDCAP       .SET    SPD_HILO        ; CPU SPEED CHANGE CAPABILITY SPD_FIXED|SPD_HILO
CPUSPDDEF       .SET    SPD_LOW        ; CPU SPEED DEFAULT SPD_UNSUP|SPD_HIGH|SPD_LOW

TMSENABLE       .SET    TRUE            ; TMS: ENABLE TMS9918 VIDEO/KBD DRIVER (TMS.ASM)

TMSMODE         .SET    TMSMODE_MBC     ; TMS: DRIVER MODE: TMSMODE_[SCG|MBC|N8|RC|RCV9958|RCKBD]
