all:
	$(MAKE) --directory DOS65
	$(MAKE) --directory software

clean:
	$(MAKE) --directory software clean
	$(MAKE) --directory DOS65 clean

pretty:
	$(MAKE) --directory software pretty
	$(MAKE) --directory DOS65 pretty
