all:
	$(MAKE) --directory software
	$(MAKE) --directory DOS65

clean:
	$(MAKE) --directory software clean
	$(MAKE) --directory DOS65 clean

pretty:
	$(MAKE) --directory software pretty
	$(MAKE) --directory DOS65 pretty
