all:
	$(MAKE) --directory utilities
	$(MAKE) --directory os

clean:
	$(MAKE) --directory utilities clean
	$(MAKE) --directory os clean

pretty:
	$(MAKE) --directory utilities pretty
	$(MAKE) --directory os pretty
