;FIXED PARAMETERS
DFLFCB	=	$107		;DEFAULT FCB
PEM	=	$103		;PEM ENTRY
BOOT	=	$100		;WARM BOOT
TEA	=	$800		;EXECUTION ORG
CCMLNG	=	2048		;CCM LENGTH
;MAIN PROGRAM
	*=	TEA

	LDY	#$00
LOOP:	LDA	START,Y
	STA	$B700,Y
	INY
	CPY	#$10
	BNE	LOOP
	JMP	$B700		
START:	
	JSR	$FFDD		; CALL S19 LOADER FROM BIOS
	JMP	BOOT
	.END

		